version: 2.1
orbs:
  matlab: mathworks/matlab@dev:8b2aa55cbfdb74319878e39ff4b57129b54bef41
  win: circleci/windows@5

executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
  windows:
    win/default

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - matlab/install:
          release: R2023b
          products: >
            Simulink
          cache: false
      - matlab/run-tests:
          source-folder: code
      - matlab/run-command:
          command: version

workflows:
  test-caching-cross-platform:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
