version: 2.1
orbs:
  matlab: mathworks/matlab@dev:5940d2ef03b9da401566ba6850f25d82933917a2
  win: circleci/windows@5

executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 15.4.0
  windows:
    win/default

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - matlab/install:
          release: R2024b
          products: >
            Simulink MATLAB_Compiler
          cache: true
      - matlab/run-tests:
          source-folder: code
      - matlab/run-command:
          command: version

workflows:
  test-caching-cross-platform:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
