version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: matlabroot;
      # - matlab/run-tests:
      #     source-folder: code
