version: 2.1
orbs:
  matlab: mathworks/matlab@dev:6b31371b4314b94b2a32a55b34450c8fa2c88360
  win: circleci/windows@5

executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
  windows:
    win/default

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Create folder
          command: |
            export FOLDER_PATH=folderName/abc
            mkdir -p $FOLDER_PATH
            echo "export FOLDER_PATH=$FOLDER_PATH" >> $BASH_ENV
            echo "~/matlab_root/$FOLDER_PATH" > ~/cache-path.txt
      - save_cache:
          key: my-folder-cache-v1
          paths:
            - $(cat ~/cache-path.txt)
      # - matlab/install:
      #     products: >
      #       SimBiology
      #     cache: true
      # - run:
      #     name: List files in workspace - Check for install-metadata.txt
      #     command: ls -alR
      # - matlab/run-tests:
      #     source-folder: code
      # - matlab/run-command:
      #     command: version

workflows:
  test-caching-cross-platform:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
