version: 2.1
orbs:
  matlab: mathworks/matlab@dev:09c6139269674b8eea3d8ed073e65b3f577e993a
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      
      # - restore_cache:
      #     name: Restore MATLAB Cache
      #     keys:
      #       - matlab-cache-key-1

      # # Check if MATLAB was restored from cache
      # - run:
      #     name: Use Cached MATLAB if Available
      #     command: |
      #       if [ -d "matlab-cache-dir" ] && [ "$(ls -A matlab-cache-dir)" ]; then
      #         echo "MATLAB cache found."
      #         CACHED_ROOT=$(find matlab-cache-dir -maxdepth 1 -mindepth 1 -type d | head -n 1)
      #         echo "$CACHED_ROOT" > matlabroot.txt
      #       else
      #         echo "No cache found. MATLAB will be installed."
      #         echo "INSTALL_NEEDED=true" >> $BASH_ENV
      #       fi
      
      - matlab/install:
          release: R2024b
          products: >
            Simulink
          cache: true
      
      # Run MATLAB and save matlabroot to a text file
      # - matlab/run-command:
      #     command: "fid = fopen('matlabroot.txt','w'); fprintf(fid, '%s', matlabroot); fclose(fid);"
      # - run:
      #     name: Save MATLAB Cache
      #     command: |
      #       MATLABROOT=$(cat matlabroot.txt)
      #       mkdir -p matlab-cache-dir
      #       cp -r "$MATLABROOT" matlab-cache-dir/
      # - save_cache:
      #     name: Cache MATLAB installation
      #     key: matlab-cache-key-1
      #     paths:
      #       - matlab-cache-dir 
      - matlab/run-tests:
          source-folder: code
