version: 2.1
orbs:
  matlab: mathworks/matlab@dev:ffb11bfa252134b7333f1200cb141050f4887ea6
  win: circleci/windows@5

executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
  windows:
    win/default

jobs:
  build:
    parameters:
      os:
        type: executor
      folder:
        type: env_var_name
        default: FOLDER_PATH
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Create folder
          command: |
            # export FOLDER_PATH=folderName/abc
            # mkdir -p $FOLDER_PATH
            # echo "export FOLDER_PATH=$FOLDER_PATH" >> $BASH_ENV
            # echo "Folder path is: $FOLDER_PATH"
            mkdir -p "${TMPDIR}/matlab-circleci-orb"
            echo "R2024b" > "${TMPDIR}/matlab-circleci-orb/install-metadata.txt"
      - save_cache:
          key: matlab-cache-{{ checksum "${TMPDIR}/matlab-circleci-orb/install-metadata.txt" }}
          paths:
            - ~/matlab_ci/matlab_root
            # - << parameters.folder >>
      # - matlab/install:
      #     products: >
      #       System_Composer
      #     cache: true
      #     release: R2024b
      # - matlab/run-tests:
      #     source-folder: code
      # - matlab/run-command:
      #     command: version

workflows:
  test-caching-cross-platform:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
