version: 2.1
orbs:
  matlab: mathworks/matlab@dev:ffb11bfa252134b7333f1200cb141050f4887ea6
  win: circleci/windows@5

executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
  windows:
    win/default

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - restore_cache:
          name: restore cache
          keys:
            - matlab-cache-1-{{ arch }}
      - run:
          name: Create folder
          command: |
            os=$(uname)
            if [[ "$os" = CYGWIN* || "$os" = MINGW* || "$os" = MSYS* ]]; then
              os="Windows"
            fi
            echo "export DETECTED_OS=$os" >> $BASH_ENV
            echo "Creating MATLAB directory for $os platform"
            mkdir -p ~/matlab-ci/matlab_root/$os
          shell: bash
      # - save_cache:
      #     key: matlab-cache-1
      #     paths:
      #       - ~/matlab_ci/matlab_root/Linux
      #       - ~/matlab_ci/matlab_root/Darwin
      #       - ~/matlab_ci/matlab_root/Windows
      #       # - << parameters.folder >>
      - run:
          name: Display detected OS
          command: |
            echo "Detected OS: $DETECTED_OS"
      
      - when:
          condition: $DETECTED_OS == "Linux"
          steps:
            - save_cache:
                name: Saving cache for linux
                key: matlab-cache-1-{{ arch }}
                paths:
                  - ~/matlab-ci/matlab_root/Linux
      - when:
          condition: $DETECTED_OS == "Darwin"
          steps:
            - save_cache:
                name: Saving cache for darwin
                key: matlab-cache-1-{{ arch }}
                paths:
                  - ~/matlab-ci/matlab_root/Darwin
      - when:
          condition: $DETECTED_OS == "Windows"
          steps:
            - save_cache:
                name: Saving cache for windows
                key: matlab-cache-1-{{ arch }}
                paths:
                  - ~/matlab-ci/matlab_root/Windows
      # - matlab/install:
      #     products: >
      #       System_Composer
      #     cache: true
      #     release: R2024b
      # - matlab/run-tests:
      #     source-folder: code
      # - matlab/run-command:
      #     command: version

workflows:
  test-caching-cross-platform:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
