version: 2.1
orbs:
  matlab: mathworks/matlab@dev:6b31371b4314b94b2a32a55b34450c8fa2c88360
  win: circleci/windows@5

executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
  windows:
    win/default

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - matlab/install:
          products: >
            SimBiology
          cache: true
      - matlab/run-tests:
          source-folder: code
      - matlab/run-command:
          command: version

workflows:
  test-caching-cross-platform:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
